"""Temporal hold-out evaluation: does the system reason correctly about the future?

Protocol
  1. Build the knowledge graph only from PEPs created before CUTOFF.
  2. Each later PEP becomes a "new input": its title + abstract, with every
     explicit "PEP NNN" mention removed so the answer is not handed over.
  3. Gold standard: the pre-cutoff corpus PEPs that the held-out PEP itself
     cites (Requires / Replaces / :pep: references). These are the prior work
     its authors judged relevant.
  4. Metrics: recall@5, recall@10, MRR of the first gold hit.

Ablations isolate what the graph contributes over plain text retrieval.
"""
from __future__ import annotations

import re
from statistics import mean

from .config import ROOT
from .extract import Builder, load_corpus
from .parse import paragraphs
from .reasoner import Engine

CUTOFF = "2023-01-01"

VARIANTS = {
    "text only (TF-IDF baseline)": dict(w_concept=0.0, w_text=1.0, spread=0.0),
    "concepts only (graph)": dict(w_concept=1.0, w_text=0.0, spread=0.0),
    "concepts + text (ranks closest PEPs / verdict)": dict(w_concept=0.55, w_text=0.45, spread=0.0),
    "concepts + text + BUILDS_ON propagation": dict(w_concept=0.55, w_text=0.45, spread=0.25),
}

REF_TYPES = ("BUILDS_ON", "REFERENCES", "CONTRASTS_WITH", "REQUIRES", "REPLACES")


def strip_pep_mentions(text: str) -> str:
    text = re.sub(r":pep:`[^`]*`", "an earlier proposal", text)
    return re.sub(r"\bPEP[\s-]*\d{1,4}\b", "an earlier proposal", text, flags=re.IGNORECASE)


def run(write: bool = True) -> str:
    docs = load_corpus()
    full = Builder(docs).build()
    train_docs = [d for d in docs if (full.nodes[f"pep:{d.number}"]["created"] or "") < CUTOFF]
    test_docs = [d for d in docs if (full.nodes[f"pep:{d.number}"]["created"] or "") >= CUTOFF]
    train_ids = {f"pep:{d.number}" for d in train_docs}
    train_graph = Builder(train_docs).build()
    engine = Engine(train_graph)

    cases = []
    for d in test_docs:
        pid = f"pep:{d.number}"
        gold = {e["dst"] for e in full.out(pid) if e["type"] in REF_TYPES and e["dst"] in train_ids}
        if not gold:
            continue
        abstract = d.top_level("Abstract")
        text = d.headers["Title"] + ". " + (" ".join(paragraphs(abstract.own_text))[:1500] if abstract else "")
        cases.append((d.number, strip_pep_mentions(text), gold))

    rows, per_case = [], {}
    for name, cfg in VARIANTS.items():
        engine.w_concept, engine.w_text = cfg["w_concept"], cfg["w_text"]
        r5, r10, rr = [], [], []
        for num, text, gold in cases:
            prof = engine.profile(text)
            ranked = [r["id"] for r in engine.related_peps(prof, k=len(engine.peps), spread=cfg["spread"])]
            r5.append(len(gold & set(ranked[:5])) / len(gold))
            r10.append(len(gold & set(ranked[:10])) / len(gold))
            first = next((i for i, p in enumerate(ranked, 1) if p in gold), None)
            rr.append(1 / first if first else 0.0)
            if "propagation" in name:
                per_case[num] = (gold, ranked[:10], r10[-1])
        rows.append((name, mean(r5), mean(r10), mean(rr)))

    L = ["# Evaluation: temporal hold-out", "",
         f"Generated by `python -m pepatlas eval`. The graph was built from the {len(train_docs)} corpus PEPs created "
         f"before {CUTOFF}. Each of the {len(cases)} later PEPs that cite pre-cutoff work was fed in as a *new input* "
         "(title + abstract, explicit PEP numbers removed). Gold = the pre-cutoff PEPs it actually cites.", "",
         f"The corpus has {len(engine.peps)} candidate PEPs in the training graph, so a random ranking would give "
         f"recall@10 of about {10 / max(1, len(engine.peps)):.2f}.", "",
         "| Variant | Recall@5 | Recall@10 | MRR |", "|---|---|---|---|"]
    L += [f"| {n} | {a:.2f} | {b:.2f} | {c:.2f} |" for n, a, b, c in rows]
    L += ["", "## Per held-out PEP (with propagation)", "", "| Held-out PEP | Gold (cited prior PEPs) | Top-10 hits | Recall@10 |",
          "|---|---|---|---|"]
    for num, (gold, top, rec) in sorted(per_case.items()):
        g = ", ".join(str(full.nodes[x]["number"]) for x in sorted(gold, key=lambda x: full.nodes[x]["number"]))
        hits = ", ".join(str(full.nodes[x]["number"]) for x in top if x in gold) or "–"
        L.append(f"| {num}: {full.nodes[f'pep:{num}']['title']} | {g} | {hits} | {rec:.2f} |")
    md = "\n".join(L) + "\n"
    if write:
        out = ROOT / "eval" / "results.md"
        out.parent.mkdir(exist_ok=True)
        out.write_text(md, encoding="utf-8")
    return md
