"""Temporal hold-out evaluation: does the system reason correctly about the future?

Protocol
  1. Build the knowledge graph only from PEPs created before CUTOFF.
  2. Each later PEP becomes a "new input": its title + abstract, with every
     explicit "PEP NNN" mention removed so the answer is not handed over.
  3. Gold standard: the pre-cutoff corpus PEPs that the held-out PEP itself
     cites (Requires / Replaces / :pep: references). These are the prior work
     its authors judged relevant.
  4. Metrics: recall@5, recall@10, MRR of the first gold hit.

Ablations isolate what the graph contributes over plain text retrieval.

A second, separate check scores the *verdicts* on the hand-labelled proposals
in eval/verdict_cases.json, using the full graph.
"""
from __future__ import annotations

import json
import re
from collections import Counter
from statistics import mean

from .config import ROOT
from .extract import Builder, load_corpus
from .parse import paragraphs
from .reasoner import Engine

CUTOFF = "2023-01-01"
VERDICT_CASES = ROOT / "eval" / "verdict_cases.json"
LABELS = ["already_exists", "in_progress", "previously_rejected", "previously_rejected_alternative",
          "extends_existing_area", "outside_known_territory"]
TRIED = {"previously_rejected", "previously_rejected_alternative"}      # both mean "this was tried and turned down"

VARIANTS = {
    "text only (TF-IDF baseline)": dict(w_concept=0.0, w_text=1.0, spread=0.0),
    "concepts only (graph)": dict(w_concept=1.0, w_text=0.0, spread=0.0),
    "concepts + text (ranks closest PEPs / verdict)": dict(w_concept=0.55, w_text=0.45, spread=0.0),
    "concepts + text + BUILDS_ON propagation": dict(w_concept=0.55, w_text=0.45, spread=0.25),
}

REF_TYPES = ("BUILDS_ON", "REFERENCES", "CONTRASTS_WITH", "REQUIRES", "REPLACES")


def strip_pep_mentions(text: str) -> str:
    text = re.sub(r":pep:`[^`]*`", "an earlier proposal", text)
    return re.sub(r"\bPEP[\s-]*\d{1,4}\b", "an earlier proposal", text, flags=re.IGNORECASE)


def run(write: bool = True) -> str:
    docs = load_corpus()
    full = Builder(docs).build()
    train_docs = [d for d in docs if (full.nodes[f"pep:{d.number}"]["created"] or "") < CUTOFF]
    test_docs = [d for d in docs if (full.nodes[f"pep:{d.number}"]["created"] or "") >= CUTOFF]
    train_ids = {f"pep:{d.number}" for d in train_docs}
    train_graph = Builder(train_docs).build()
    engine = Engine(train_graph)

    cases = []
    for d in test_docs:
        pid = f"pep:{d.number}"
        gold = {e["dst"] for e in full.out(pid) if e["type"] in REF_TYPES and e["dst"] in train_ids}
        if not gold:
            continue
        abstract = d.top_level("Abstract")
        text = d.headers["Title"] + ". " + (" ".join(paragraphs(abstract.own_text))[:1500] if abstract else "")
        cases.append((d.number, strip_pep_mentions(text), gold))

    rows, per_case = [], {}
    for name, cfg in VARIANTS.items():
        engine.w_concept, engine.w_text = cfg["w_concept"], cfg["w_text"]
        r5, r10, rr = [], [], []
        for num, text, gold in cases:
            prof = engine.profile(text)
            ranked = [r["id"] for r in engine.related_peps(prof, k=len(engine.peps), spread=cfg["spread"])]
            r5.append(len(gold & set(ranked[:5])) / len(gold))
            r10.append(len(gold & set(ranked[:10])) / len(gold))
            first = next((i for i, p in enumerate(ranked, 1) if p in gold), None)
            rr.append(1 / first if first else 0.0)
            if "propagation" in name:
                per_case[num] = (gold, ranked[:10], r10[-1])
        rows.append((name, mean(r5), mean(r10), mean(rr)))

    L = ["# Evaluation: temporal hold-out", "",
         f"Generated by `python -m pepatlas eval`. The graph was built from the {len(train_docs)} corpus PEPs created "
         f"before {CUTOFF}. Each of the {len(cases)} later PEPs that cite pre-cutoff work was fed in as a *new input* "
         "(title + abstract, explicit PEP numbers removed). Gold = the pre-cutoff PEPs it actually cites.", "",
         f"The corpus has {len(engine.peps)} candidate PEPs in the training graph, so a random ranking would give "
         f"recall@10 of about {10 / max(1, len(engine.peps)):.2f}.", "",
         "| Variant | Recall@5 | Recall@10 | MRR |", "|---|---|---|---|"]
    L += [f"| {n} | {a:.2f} | {b:.2f} | {c:.2f} |" for n, a, b, c in rows]
    L += ["", "## Per held-out PEP (with propagation)", "", "| Held-out PEP | Gold (cited prior PEPs) | Top-10 hits | Recall@10 |",
          "|---|---|---|---|"]
    for num, (gold, top, rec) in sorted(per_case.items()):
        g = ", ".join(str(full.nodes[x]["number"]) for x in sorted(gold, key=lambda x: full.nodes[x]["number"]))
        hits = ", ".join(str(full.nodes[x]["number"]) for x in top if x in gold) or "–"
        L.append(f"| {num}: {full.nodes[f'pep:{num}']['title']} | {g} | {hits} | {rec:.2f} |")
    L += ["", *verdict_section(Engine(full))]
    md = "\n".join(L) + "\n"
    if write:
        out = ROOT / "eval" / "results.md"
        out.parent.mkdir(exist_ok=True)
        out.write_text(md, encoding="utf-8")
    return md


def load_verdict_cases() -> list[dict]:
    return json.loads(VERDICT_CASES.read_text(encoding="utf-8"))["cases"]


def verdict_section(engine: Engine) -> list[str]:
    cases = load_verdict_cases()
    rows, confusion = [], Counter()
    strict = lenient = tried = pep_cases = pep_top1 = pep_top3 = 0
    for c in cases:
        r = engine.assess(c["text"])
        got, want = r["verdict"]["label"], c["expected_label"]
        ok = got == want
        accepted = ok or got in c.get("also_acceptable", [])
        strict += ok
        lenient += accepted
        tried += ok or (got in TRIED and want in TRIED)
        confusion[want, got] += 1
        # The PEP the verdict rests on comes first, then the closest PEPs.
        cited = [r["verdict"].get("basis", {}).get("pep")] + [p["pep"] for p in r["closest_peps"]]
        cited = [p for i, p in enumerate(cited) if p and p not in cited[:i]]
        if c.get("expected_pep"):
            pep_cases += 1
            pep_top1 += cited[:1] == [c["expected_pep"]]
            pep_top3 += c["expected_pep"] in cited[:3]
        rows.append(f"| {c['id']} | {want} | {got} | {'yes' if ok else ('acceptable' if accepted else 'no')} "
                    f"| {c.get('expected_pep') or '–'} | {', '.join(map(str, cited[:3])) or '–'} |")
    n = len(cases)
    short = {l: "".join(w[0] for w in l.split("_")) for l in LABELS}
    L = ["# Evaluation: verdict accuracy", "",
         f"{n} hand-labelled proposals in `eval/verdict_cases.json`, written and frozen before the system was run "
         "on them, and disjoint from the golden tests and examples used for tuning. Full graph.", "",
         "| Metric | Score |", "|---|---|",
         f"| Verdict exactly right | {strict}/{n} ({strict / n:.0%}) |",
         f"| Right or a listed acceptable alternative | {lenient}/{n} ({lenient / n:.0%}) |",
         f"| Right, counting both kinds of rejection as one (\"was tried\") | {tried}/{n} ({tried / n:.0%}) |",
         f"| Expected PEP is the first one cited | {pep_top1}/{pep_cases} |",
         f"| Expected PEP among the first three cited | {pep_top3}/{pep_cases} |", "",
         "## Confusion matrix (rows: expected, columns: system)", "",
         "| expected → got | " + " | ".join(short[l] for l in LABELS) + " |",
         "|---|" + "---|" * len(LABELS)]
    L += [f"| {l} | " + " | ".join(str(confusion[l, g] or "·") for g in LABELS) + " |" for l in LABELS]
    L += ["", "Abbreviations: " + ", ".join(f"{short[l]} = {l}" for l in LABELS) + ".", "",
          "## Per case", "", "| Case | Expected | Got | Correct | Expected PEP | PEPs cited first |",
          "|---|---|---|---|---|---|", *rows]
    return L
