"""Write the knowledge state in inspectable forms:

- knowledge/graph.json   the full graph (schema, nodes, edges with provenance)
- knowledge/schema.json  the entity/relationship schema on its own
- knowledge/summary.md   a human-readable tour of what the system knows
- knowledge/graph.html   a self-contained interactive viewer
"""
from __future__ import annotations

import json
from collections import Counter, defaultdict

from .config import GRAPH_PATH, KNOWLEDGE_DIR
from .graph import KnowledgeGraph


def write_all(g: KnowledgeGraph):
    g.save(GRAPH_PATH)
    data = g.to_json()
    (KNOWLEDGE_DIR / "schema.json").write_text(json.dumps(data["schema"], indent=2) + "\n", encoding="utf-8", newline="\n")
    (KNOWLEDGE_DIR / "summary.md").write_text(summary_md(g), encoding="utf-8", newline="\n")
    try:
        from .viewer import write_viewer
        write_viewer(g, KNOWLEDGE_DIR / "graph.html")
    except ImportError:
        pass


def summary_md(g: KnowledgeGraph) -> str:
    data = g.to_json()
    peps = sorted((n for n in g.of_type("PEP") if n.get("in_corpus")), key=lambda n: n["number"])
    L = ["# Knowledge state summary", "",
         "Generated by `python -m pepatlas build` from `graph.json`. This file is a readable view of the graph; "
         "`graph.json` is the source of truth.", "",
         f"Source: {g.meta.get('source')}", "", "## Size", "", "| Node type | Count |", "|---|---|"]
    L += [f"| {k} | {v} |" for k, v in data["stats"]["nodes"].items()]
    L += ["", "| Edge type | Count | Rule |", "|---|---|---|"]
    L += [f"| {k} | {v} | {data['schema']['edge_types'][k]['rule']} |" for k, v in data["stats"]["edges"].items()]

    L += ["", "## Concept lineages", "",
          "For each concept: which PEP introduced it, which extended it, and which proposals about it are not "
          "(or not yet) accepted.", "", "| Concept | Introduced | Extended | Proposed (not accepted) | Rejected ideas about it |",
          "|---|---|---|---|---|"]
    for c in sorted(g.of_type("Concept"), key=lambda c: (c["category"], c["label"])):
        rel = defaultdict(list)
        for e in g.into(c["id"]):
            if e["type"] in ("INTRODUCES", "EXTENDS", "PROPOSES"):
                rel[e["type"]].append(g.nodes[e["src"]]["number"])
        ideas = len(g.into(c["id"], "ABOUT"))
        if not rel and not ideas:
            continue
        fmt = lambda xs: ", ".join(str(x) for x in sorted(xs)) or "–"
        L.append(f"| {c['label']} | {fmt(rel['INTRODUCES'])} | {fmt(rel['EXTENDS'])} | {fmt(rel['PROPOSES'])} | {ideas} |")

    L += ["", "## PEPs in the corpus", "", "| PEP | Title | Status | Year | Focus | Builds on | Rejected ideas |",
          "|---|---|---|---|---|---|---|"]
    for n in peps:
        builds = sorted(g.nodes[e["dst"]]["number"] for e in g.out(n["id"], "BUILDS_ON"))
        L.append(f"| {n['number']} | {n['title']} | {n['status']} | {n['year']} | "
                 f"{', '.join(n.get('focus_concepts', [])) or '–'} | {', '.join(map(str, builds)) or '–'} | "
                 f"{len(g.out(n['id'], 'CONSIDERED'))} |")

    L += ["", "## Rejected ideas that later accepted PEPs revisited", ""]
    for e in sorted(g.edges, key=lambda e: e["src"]):
        if e["type"] == "REVISITED_BY":
            i, p = g.nodes[e["src"]], g.nodes[e["dst"]]
            L.append(f"- PEP {i['pep']} rejected *{i['title']}* → revisited by PEP {p['number']} ({p['title']}); "
                     f"shared: {', '.join(e['shared_concepts'])}; confidence {e['confidence']}")

    L += ["", "## Most common objection types", "", "| Concern | Raised by rejected ideas | Raised in compat/open-issues/decisions |",
          "|---|---|---|"]
    by = defaultdict(Counter)
    for e in g.edges:
        if e["type"] == "RAISES":
            by[e["dst"]]["idea" if e["src"].startswith("idea:") else "pep"] += 1
    for cid, cnt in sorted(by.items(), key=lambda kv: -sum(kv[1].values())):
        L.append(f"| {g.nodes[cid]['label']} | {cnt['idea']} | {cnt['pep']} |")

    L += ["", "## Most involved people", ""]
    inv = Counter()
    for e in g.edges:
        if e["type"] in ("AUTHORED_BY", "SPONSORED_BY", "DECIDED_BY"):
            inv[e["dst"]] += 1
    L += [f"- {g.nodes[p]['name']}: {k} roles" for p, k in inv.most_common(12)]
    return "\n".join(L) + "\n"
